### PR TITLE
Upgrading site to jumbo-jekyll-theme 6.0.2.1 (bootstrap 4 / jekyll 4)

### PR DESCRIPTION
**Pull request by kylekirkby**
As requested, the site has been updated to use the latest version of the jumbo-jekyll-theme.

### CODE REVIEW

**Review by pcolmer — APPROVED** [review]

**Comment by pcolmer** [comment]
Thanks, @kylekirkby, for getting this done quickly.

I'd like @nathalie-ckc to approve the preview site (http://production-openampproject-org-58.websitepreview.linaro.org/) before this change is merged, please.

**Comment by nathalie-ckc** [comment]
Hi @kylekirkby ,

Is it possible to keep the old footer that had useful links?
image

After this is published, I'll have to fix some of the blog posts that I used the social-media-image.png for because that would appear as just the logo in the old view (I guess taking advantage of possibly un-intended behavior) and now it shows up as an image of the website.  Intent was to have the openamp logo.

Thanks & regards,
Nathalie

**Comment by kylekirkby** [comment]
> Hi @kylekirkby ,
> 
> Is it possible to keep the old footer that had useful links?
> image
> 
> After this is published, I'll have to fix some of the blog posts that I used the social-media-image.png for because that would appear as just the logo in the old view (I guess taking advantage of possibly un-intended behavior) and now it shows up as an image of the website. Intent was to have the openamp logo.
> 
> Thanks & regards,
> Nathalie

Hi @nathalie-ckc ,

Could you please verify the changes made through the latest commits are what you're looking for?

Best regards,

Kyle

**Review by nathalie-ckc — APPROVED** [review]
Hi @kylekirkby ,
Thanks! The changes look good to me.

**Pull request merged**
