### PR TITLE
Blog posts on presentations at Zephyr Dev Summit 2022 and ELC NA 2022

### PR DESCRIPTION
**Pull request by nathalie-ckc**
Create a blog post with links to the PDF and video for Dan's presentation on hypervisorless virtio at the 2022 Zephyr Developer Summit.

### CODE REVIEW

**Comment by nathalie-ckc** [comment]
Hi @wmamills , 

This PR is to address issue #84 .  I made 3 blog posts for each of the 2022 presentations that we're calling out.

I omitted the 2017 presentation by Stefano since he's done many since 2017 and he's at a different company for that one.  Was there a specific reason why you suggested that one for the other presentations by Stefano that folks might want to watch?  Please let me know if you feel strongly about including that one, or if I can go ahead & merge the changes as shown in the Deploy Preview check.

Thanks!

**Review by wmamills — APPROVED** [review]
I read through and double checked the links.
I did not render it locally but I assume it is OK.

**Comment by kylekirkby** [comment]
> I read through and double checked the links. I did not render it locally but I assume it is OK.

If you click the "Show all checks" link below, you can get a "Deploy Preview" link:

E.g
https://production-openampproject-org-89.ghactions.linaro.org/

**Comment by nathalie-ckc** [comment]
Thanks, Bill & Kyle!
-Nathalie

**Pull request merged**
